name: Automatic Gradle Testing
on: [push]

jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/setup-java@v1
            with:
              java-version: '17'
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
